= Deliberate Action
Bill Turner
:toc:
:toc-placement!:

toc::[]

== Overview ==
In the early days of Agile, you would often hear an argument about whether software development is an
art or a craft. In my opinion, it is neither. It seems to me to more closely resemble a learning activity,
one that is closer to scientific experimentation. You have a hypothesis of how something should work,
you build a test apparatus, and you test hypotheses.

Listening to colleagues during the midst of a project, or even something as small as a story or task, you
will often hear them talk of what they learned.

This tool attempts to incorporate deliberate practice with others - most notably Agile like retrospective
questions. Here, the iterations are quite small. This allows for a more immediate feedback of each
session. Thinking about what you could have done better is the part of the deliberative process. The
other is having that fresh in your mind as you being in your next session. Over time, it should be possible
to see patterns. And, as a side benefit, could make your Agile retrospectives more productive for, as I
have often observed, teams often have trouble adequately identifying what happened near the beginning
of a sprint - unless it was very significant.

While I don't know if there is great evidence supporting the Pomodoro like short iterations and breaks, it
feels right. Perhaps that is the software engineer in me for I believe things should be kept as simple as
possible. Planning activities that are of short duration should help foster a laser like focus on what
can be achieved, keeping them simple, understandable, unsurprising. And, importantly, easy to reflect
upon.

Each of these short sessions are followed by, what I call, After Action reports - a term borrowed from
the military. They allow you to consider what happened, what you want to reinforce and what you can do
to improve. This is the reflection activity.

I have many further thoughts about how this should eventually work and look. But, for now, I am trying to
keep it simple so that I may _learn_, _reflect_ and modify my _practice_.

==== Further References
* https://www.apa.org/monitor/2018/06/good-timing[Chronotypes]
* https://www.nytimes.com/2011/01/21/science/21memory.html[Have a learning template? Study, practice, test?]
* When: The Scientific Secrets of Perfect Timing by Daniel H. Pink
* Peak: Secrets from the New Science of Expertise by Anders Ericsson and Robert Pool



// include::docs/FAQ.adoc[]

== Considerations For Future Releases ==
. A goal setting template? How would that work?
. Works on multiple platforms:
.. Works on both smart phones and web pages.
.. Data updated on one device is immediately propogated to all devices.
. Provides an implementation of related task (activity) and time management practices:
.. Pomodoro planning
.. Urgent/Important matrix - (Eisenhower & Covey)
.. After action report
.. Time Tracking
.. Incorporates knowledge of Chronotypes
. Activities that
.. Contain zero or more sub-activites
.. Time recording at any level
. Configurable:
.. Pomodoro interval lengths
.. Features used in activity
.. Activities can be scheduled with specific start/stop times, complete with alarms.
.. Templates exist to quickly setup various types of activities.
... Workday templates, for example, could have time allotted to recurring/regular activities.
. Integrate with google calendars


== Ideas, Issues and Opportunities ==
None that are not listed above.

== Version 0.0.1 (2019-01-01)
.Release highlights
Initial release

.Other additions and changes
- none


.Bug fixes
- none
