= Task Tracking Extraordinaire
Bill Turner
:toc:
:toc-placement!:

toc::[]

== Overview ==
The intent is to have a simple tool that:
. Works on multiple platforms:
.. Works on both smart phones and web pages.
.. Data updated on one device is immediately propogated to all devices.
. Provides an implementation of related task and time management tools:
.. Pomodoro planning
.. Urgent/Important matrix - (Eisenhower & Covey)
.. After action report
.. Time Tracking
. Multiple projects
.. Tasks and subtasks
.. Time recording at any level
. Configurable:
.. Pomodoro interval lengths
.. Features used in task
.. Tasks/projects can be scheduled with specific start/stop times, complete with alarms.
.. Templates exist to quickly setup various types of tasks/projects.

The use of urgent/important task identification allows you to effectively prioritize tasks.

The philosophy is that the smaller the unit of work, the better. By planning tasks that are no more
than the Pomodoro allotted time, they are kept simple, understandable, unsurprising. 

After action reports are essential. They allow you to consider what happened, what you want to reinforce
and what you can do to improve. Coupling this to the Pomodoro intervals means it will be fresh in your
mind and can help you see patterns.

Through the use of templates and configuration options, tasks can be tracked using any or all of these
features. You can set up a task/project that could last month or even years. Or you could set up one that
is little more than a reminder to have a block of time for those things that are truly important, like
spending time with your family.

include::STYLE_GUIDE.asciidoc[]

include::TODO.asciidoc[]
